# Generated by Django 5.0.2 on 2024-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slot', models.IntegerField()),
                ('parked', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
