# Generated by Django 5.0.2 on 2024-02-27 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slots_alter_cars_car_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
