# Generated by Django 5.0.2 on 2024-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slot', models.IntegerField()),
                ('booked_slot', models.IntegerField()),
            ],
        ),
    ]
