# Generated by Django 5.0.2 on 2024-05-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='spots',
            name='entry',
            field=models.DateTimeField(null=True),
        ),
    ]
